### ISSUE TITLE
生成代码无法访问到数据库表？

### ISSUE THREAD

**Issue by isGov** [taozhi1010/nest-admin#9]
后台报错 **ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (D:\govi\nest若依\nest-admin\server\node_modules\express-rate-limit\dist\index.cjs:166:13)
    at Object.wrappedValidations.<computed> [as xForwardedForHeader] (D:\govi\nest若依\nest-admin\server\node_modules\express-rate-limit\dist\index.cjs:324:22)
    at Object.keyGenerator (D:\govi\nest若依\nest-admin\server\node_modules\express-rate-limit\dist\index.cjs:579:20)
    at D:\govi\nest若依\nest-admin\server\node_modules\express-rate-limit\dist\index.cjs:629:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at D:\govi\nest若依\nest-admin\server\node_modules\express-rate-limit\dist\index.cjs:611:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'**

**Comment by taozhi1010** [comment]
已修复
